package discovery

func fallbackVenues() []Venue {
	return []Venue{
		{
			ID:               "11111111-1111-4111-8111-111111111111",
			Name:             "Banh Mi Hem",
			Slug:             "banh-mi-hem-nguyen-trai-district-1",
			ShortDescription: "Late-night banh mi spot trending on social video.",
			About:            "A compact street-food venue known for grilled pork banh mi, quick service, and strong late-night local buzz near Nguyen Trai.",
			Address:          "12 Nguyen Trai",
			City:             "Thành phố Hồ Chí Minh",
			District:         "Quận 1",
			Latitude:         10.7712,
			Longitude:        106.6899,
			Categories:       []string{"street_food", "banh_mi"},
			PriceLevel:       1,
			AvgPriceMinVND:   30000,
			AvgPriceMaxVND:   80000,
			Currency:         "VND",
			SocialVideoCount: 42,
			SocialVideos: []SocialVideo{
				{
					ID:            "33333333-3333-4333-8333-333333333331",
					Platform:      "tiktok",
					URL:           "https://www.tiktok.com/@tikfood/video/banh-mi-hem-1",
					CreatorHandle: "@tikfood",
					Caption:       "Late-night banh mi with grilled pork near Nguyen Trai.",
					ThumbnailURL:  "",
					ViewCount:     120000,
					LikeCount:     8200,
					PublishedAt:   "2026-05-20T10:00:00Z",
				},
				{
					ID:            "33333333-3333-4333-8333-333333333332",
					Platform:      "instagram",
					URL:           "https://www.instagram.com/reel/banh-mi-hem-2/",
					CreatorHandle: "@saigonbites",
					Caption:       "Crispy banh mi pate and grilled pork combo.",
					ThumbnailURL:  "",
					ViewCount:     80000,
					LikeCount:     5100,
					PublishedAt:   "2026-05-22T10:00:00Z",
				},
			},
			TrendScore:     92,
			TrendingDishes: []string{"banh mi thit nuong", "banh mi pate"},
			AISummary:      "Trending for late-night banh mi clips with strong local social proof.",
		},
		{
			ID:               "22222222-2222-4222-8222-222222222222",
			Name:             "Pho Bo Nguyen",
			Slug:             "pho-bo-nguyen-le-van-sy-district-3",
			ShortDescription: "Breakfast pho shop with consistent creator mentions.",
			About:            "A neighborhood pho venue known for clear broth, beef toppings, and steady breakfast traffic from local regulars and food creators.",
			Address:          "88 Le Van Sy",
			City:             "Thành phố Hồ Chí Minh",
			District:         "Quận 3",
			Latitude:         10.7864,
			Longitude:        106.6767,
			Categories:       []string{"noodle", "pho"},
			PriceLevel:       1,
			AvgPriceMinVND:   50000,
			AvgPriceMaxVND:   120000,
			Currency:         "VND",
			SocialVideoCount: 35,
			SocialVideos: []SocialVideo{
				{
					ID:            "44444444-4444-4444-8444-444444444441",
					Platform:      "tiktok",
					URL:           "https://www.tiktok.com/@tikfood/video/pho-bo-nguyen-1",
					CreatorHandle: "@tikfood",
					Caption:       "Breakfast pho with clear broth and rare beef.",
					ThumbnailURL:  "",
					ViewCount:     95000,
					LikeCount:     6900,
					PublishedAt:   "2026-05-19T23:00:00Z",
				},
			},
			TrendScore:     87,
			TrendingDishes: []string{"pho bo tai", "pho bo vien"},
			AISummary:      "Popular for breakfast pho videos and consistent creator mentions.",
		},
	}
}
